apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifactory

resources:
  - namespace.yaml
  - artifactory/artifactory-pv.yaml
  - artifactory/artifactory-service.yaml
  - artifactory/artifactory-statefulset.yaml
  - artifactory/artifactory-ingress.yaml
  - postgres/postgres-pv.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-statefulset.yaml
