apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifactory

resources:
  - namespace.yaml
  - artifactory/artifactory-pvc.yaml
  - artifactory/artifactory-helmrelease.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres-helmrelease.yaml