apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/artifactory_data   # Make sure this folder exists on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cakers-worker-1  # Node where the path exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-pvc
  namespace: artifactory  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
