apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mystory
  namespace: mystory
spec:
  interval: 5m
  chart:
    spec:
      chart: mystory
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: mystory-harbor
        namespace: flux-system      
  values:
    replicaCount: 1
    image:
      repository: cakes1978/mystory
      tag: "0.1.0"
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      port: 80
    resources: {}
