apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artifactory-ingress
spec:
  rules:
  - host: artifactory.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: artifactory
            port:
              number: 8081
