apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-redis-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty
  hostPath:
    path: /mnt/data/harbor-redis-data
  claimRef:
    name: data-harbor-redis-0
    namespace: harbor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cakers-worker-1.lab.local       
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-trivy-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty
  hostPath:
    path: /mnt/data/harbor-trivy-data
  claimRef:
    name: data-harbor-trivy-0
    namespace: harbor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cakers-worker-1.lab.local       
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-database-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty
  hostPath:
    path: /mnt/data/harbor-database-data
  claimRef:
    name: database-data-harbor-database-0
    namespace: harbor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cakers-worker-2.lab.local    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-jobservice-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty
  hostPath:
    path: /mnt/data/harbor-jobservice-data
  claimRef:
    name: harbor-jobservice
    namespace: harbor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cakers-worker-3.lab.local    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-registry-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty
  hostPath:
    path: /mnt/data/harbor-registry-data
  claimRef:
    name: harbor-registry
    namespace: harbor
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cakers-worker-3.lab.local     
