apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty
  hostPath:
    path: /mnt/data/harbor-data
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - cakers-worker-1.lab.local

