apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  chart:
    spec:
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    expose:
      type: loadBalancer
      name: harbor
      tls:
        enabled: false
    registry:
      affinity:
        nodeSelector:
        kubernetes.io/hostname: cakers-worker-3.lab.local
    trivy:
      affinity:
        nodeSelector:
        kubernetes.io/hostname: cakers-worker-1.lab.local
    database:
      affinity:
        nodeSelector:
        kubernetes.io/hostname: cakers-worker-2.lab.local    
    redis:
      affinity:
        nodeSelector:
        kubernetes.io/hostname: cakers-worker-1.lab.local
    jobservice:
      affinity:
        nodeSelector:
        kubernetes.io/hostname: cakers-worker-3.lab.local

