apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  chart:
    spec:
      chart: harbor
      version: "1.19.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    externalURL: http://192.168.56.200
    expose:
      type: loadBalancer
      name: harbor
      tls:
        enabled: false
    registry:
      nodeSelector:
        kubernetes.io/hostname: cakers-worker-3.lab.local
    trivy:
      nodeSelector:
        kubernetes.io/hostname: cakers-worker-1.lab.local
    database:
      nodeSelector:
        kubernetes.io/hostname: cakers-worker-2.lab.local
    redis:
      nodeSelector:
        kubernetes.io/hostname: cakers-worker-1.lab.local
    jobservice:
      nodeSelector:
        kubernetes.io/hostname: cakers-worker-3.lab.local
