apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: artifactory-mystory
  namespace: flux-system
spec:
  interval: 5m
  url: http://artifactory-oss.artifactory:8082/artifactory/mystory-virtual
  secretRef:
    name: artifactory-mystory-credentials

