apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Not curently using artifactory, OSS version is too limited. Switched to Harbor
  # - jfrog.yaml
  - harbor.yaml
  - metallb.yaml
  - grafana-alloy.yaml
  - mystory-harbor-repo.yaml
  - sealed-secrets.yaml
