apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: database
spec:
  chart:
    spec:
      chart: postgresql
      version: 15.3.0           # update to a chart version that exists
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  values:
    global:
      postgresql:
        postgresqlDatabase: artifactory
        postgresqlUsername: artifactory
        postgresqlPassword: artifactory123
    primary:
      persistence:
        enabled: true
        existingClaim: postgres-pv   # use the PV we created
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - cakers-worker-2.lab.local
