apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Artifactory is being removed and replaced with Harbor. Artfiactory OSS is too limited for what I want, but at least
  # I got it up and running. I won't remove the source from this repo because useful stuff.
  # - artifactory/
  - grafana-alloy/
  # - harbor/
  - mystory/
