apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-oss
  namespace: artifactory
spec:
  interval: 5m
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  chart:
    spec:
      chart: artifactory-oss
      version: "107.133.12"
      sourceRef:
        kind: HelmRepository
        name: jfrog
        namespace: flux-system
  values:
    artifactory:
      artifactory:
        nodeSelector:
          kubernetes.io/hostname: cakers-worker-1.lab.local
      postgresql:
        primary:
          nodeSelector:
            kubernetes.io/hostname: cakers-worker-2.lab.local
  valuesFrom:
    - kind: Secret
      name: artifactory-secrets
      valuesKey: artifactoryPassword
      targetPath: artifactory.postgresql.auth.password
    - kind: Secret
      name: artifactory-secrets
      valuesKey: postgresPassword
      targetPath: artifactory.postgresql.auth.postgresPassword
    - kind: Secret
      name: artifactory-secrets
      valuesKey: artifactoryMasterKey
      targetPath: artifactory.artifactory.masterKey
    - kind: Secret
      name: artifactory-secrets
      valuesKey: artifactoryJoinKey
      targetPath: artifactory.artifactory.joinKey      
