apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
resources:
  - namespace.yaml
  - pv-artifactory.yaml
  - pv-postgresql.yaml
  - pvc-artifactory.yaml
  - pvc-postgresql.yaml
  - helmrelease.yaml
