apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-artifactory
  namespace: artifactory
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/artifactory-data/artifactory
  persistentVolumeReclaimPolicy: Retain
