apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: artifactory
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/artifactory-data/postgresql
  persistentVolumeReclaimPolicy: Retain
