apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-postgresql
  storageClassName: ""
