apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-volume-artifactory-oss-artifactory-0
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-artifactory
  storageClassName: ""
