apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: grafana-alloy
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }
    http {
        listen_addr = "0.0.0.0:12345"
    }
