apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: grafana-alloy
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    prometheus.exporter.unix "local_system" { }

    prometheus.scrape "scrape_metrics" {
      targets         = prometheus.exporter.unix.local_system.targets
      forward_to      = [prometheus.relabel.metrics_service.receiver]
      scrape_interval = "10s"
    }

    prometheus.remote_write "metrics_service" {
        endpoint {
            url = "http://localhost:9090/api/v1/write"

            // basic_auth {
            //   username = "admin"
            //   password = "admin"
            // }
        }
    }

    