apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
  namespace: grafana-alloy
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana/alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-alloy
        namespace: flux-system
  values:
    alloy:
      configMap:
        create: false
        name: grafana-alloy-config

