apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
  namespace: grafana-alloy
spec:
  interval: 5m
  chart:
    spec:
      chart:  alloy
      version: "1.8.2"
      sourceRef:
        kind: HelmRepository
        name: grafana-alloy
        namespace: flux-system
  values:
    alloy:
      configMap:
        create: false
        name: grafana-alloy-config
    controller:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      affinity:          
        nodeAffinity:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - cakers-cp-1.lab.local          
    service:
      type: LoadBalancer

